config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Authentication
  devise_for :users

  # Core Resources
  resources :groups do
    member do
      get 'digests'
      get 'questions'
      post 'send_invite'
      post 'toggle_member_status/:member_id', to: 'groups#toggle_member_status', as: 'toggle_member_status'
    end

    # Nested cycles resource
    resources :cycles, controller: 'group_cycles', only: [:index] do
      member do
        post 'close_early'
      end
      collection do
        post 'send_manual_question'
        post 'send_manual_digest/:cycle_id', to: 'group_cycles#send_manual_digest', as: 'send_manual_digest'
        post 'pause'
        post 'resume'
        patch 'update_mode'
      end
    end

    get 'accept_invitation', on: :collection
    resources :members, only: [:show], controller: 'group_members'
    scope module: :groups do
      resources :questions, only: [:show] do
        member do
          post 'vote'
          post 'add_tag'
          delete 'remove_tag'
          delete 'unvote'
        end
      end
    end
  end
  resources :questions do
    member do
      post 'send', to: 'questions#send_to_group', as: 'send'
    end
  end
  resources :question_records
  resources :answers
  resources :users

  # Custom Actions
  post 'send_random', to: 'questions#send_random_question'
  post 'inbound', to: 'email_response#create_from_inbound_hook'
  post 'answer', to: 'answers#create_from_form'

  # Admin Section
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'

    get 'dashboard/visits', to: 'dashboard#visits'
    get 'dashboard/emails', to: 'dashboard#emails'
    get 'dashboard/events', to: 'dashboard#events'
    get 'dashboard/users', to: 'dashboard#users'
    get 'dashboard/users/:id', to: 'dashboard#user_details', as: 'dashboard_user_details'
    get 'dashboard/email_reply_stats', to: 'dashboard#email_reply_stats', as: 'email_reply_stats'

    # Chart data endpoints
    get 'dashboard/daily_visits_data', to: 'dashboard#daily_visits_data'
    get 'dashboard/hourly_visits_data', to: 'dashboard#hourly_visits_data'
    get 'dashboard/countries_data', to: 'dashboard#countries_data'
    get 'dashboard/devices_data', to: 'dashboard#devices_data'
    get 'dashboard/emails_data', to: 'dashboard#emails_data'
    get 'dashboard/events_data', to: 'dashboard#events_data'
    get 'dashboard/regions_data', to: 'dashboard#regions_data'
    get 'dashboard/cities_data', to: 'dashboard#cities_data'
    get 'dashboard/user_activity_data', to: 'dashboard#user_activity_data'
    get 'dashboard/group_activity_data', to: 'dashboard#group_activity_data'

    get 'recent_signups', to: 'dashboard#recent_signups'

    get 'dashboard/groups', to: 'dashboard#groups'
    get 'dashboard/group_details/:id', to: 'dashboard#group_details', as: 'group_details'
  end

  # Development Tools
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/groups/questions_controller.rb
module Groups
  class QuestionsController < ApplicationController
    before_action :set_group
    before_action :set_question

    def show
      # Get usage statistics
      @usage_count = @group.question_records.where(question_id: @question.id).count

      # Get all instances this question was asked
      @question_records = @group.question_records
        .where(question_id: @question.id)
        .order(created_at: :desc)

      # Simple total answers count
      @total_answers = Answer.where(question_record_id: @question_records.pluck(:id)).count

      # Get voting information
      @group_question = @group.group_questions.find_by(question: @question)
      @voter_count = @group_question&.group_question_votes&.count || 0

      # Get similar questions based on tags
      @similar_questions = Question.joins(:tags)
        .where(tags: { id: @question.tags.pluck(:id) })
        .where.not(id: @question.id)
        .distinct
        .limit(5)
    end

    def add_tag
      # Ensure user is a member of the group
      unless @group.users.include?(current_user)
        redirect_to group_question_path(@group, @question), alert: "Only group members can add tags"
        return
      end

      tag = Tag.find_or_create_by(name: params[:tag_name].strip.downcase)

      unless @question.group_question_tags.exists?(group: @group, tag: tag)
        @question.group_question_tags.create!(
          group: @group,
          tag: tag,
          created_by: current_user  # Track who created the tag
        )
      end

      @question.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to group_question_path(@group, @question) }
      end
    end

    def remove_tag
      # Only group leaders can remove tags
      unless current_user == @group.leader
        redirect_to group_question_path(@group, @question), alert: "Only group leaders can remove tags"
        return
      end

      tag = Tag.find(params[:tag_id])
      group_tag = @question.group_question_tags.find_by(group: @group, tag: tag)
      group_tag&.destroy

      @question.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to group_question_path(@group, @question) }
      end
    end

    def vote
      @group_question = @group.group_questions.find_or_create_by!(question: @question)

      if @group_question.voted_by?(current_user)
        redirect_back(fallback_location: group_question_path(@group, @question), alert: "You have already voted for this question")
        return
      end

      vote = @group_question.group_question_votes.build(user: current_user)

      if vote.save
        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: [
              turbo_stream.replace("vote-button-area-#{@group_question.id}",
                partial: 'groups/questions/vote_button_area',
                locals: { group: @group, question: @question, group_question: @group_question }
              ),
              turbo_stream.replace_all(".question-#{@question.id}-vote-count",
                @group_question.vote_count.to_s)
            ]
          }
          format.html { redirect_back(fallback_location: group_question_path(@group, @question), notice: "Vote recorded") }
        end
      else
        redirect_back(fallback_location: group_question_path(@group, @question), alert: vote.errors.full_messages.to_sentence)
      end
    end

    def unvote
      @group_question = @group.group_questions.find_by!(question: @question)
      vote = @group_question.group_question_votes.find_by(user: current_user)

      if vote&.destroy
        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: [
              turbo_stream.replace("vote-button-area-#{@group_question.id}",
                partial: 'groups/questions/vote_button_area',
                locals: { group: @group, question: @question, group_question: @group_question }
              ),
              turbo_stream.replace_all(".question-#{@question.id}-vote-count",
                @group_question.vote_count.to_s)
            ]
          }
          format.html { redirect_back(fallback_location: group_question_path(@group, @question), notice: "Vote removed") }
        end
      else
        redirect_back(fallback_location: group_question_path(@group, @question), alert: "Unable to remove vote")
      end
    end

    private

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_question
      @question = Question.find(params[:id])
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :questions, :digests]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # Calculate participation counts for each user (needed for both tabs)
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Redirect to the appropriate tab action
    if params[:tab] == 'questions'
      redirect_to questions_group_path(@group, request.query_parameters.except(:tab))
    elsif params[:tab] == 'cycles' && current_user == @group.leader
      redirect_to group_cycles_path(@group, request.query_parameters.except(:tab))
    else
      redirect_to digests_group_path(@group, request.query_parameters.except(:tab))
    end
  end

  # GET /groups/1/digests
  def digests
    # Calculate participation counts for each user
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Q&A Digests tab
    base_query = @group.question_records
      .includes(:question, :answers)

    # Apply sorting for Q&A Digests
    @question_records = case params[:sort]
    when 'date_asc'
      base_query.order(created_at: :asc)
    when 'answers_desc'
      base_query
        .select('question_records.*, COUNT(DISTINCT answers.id) as answers_count')
        .left_joins(:answers)
        .group('question_records.id')
        .order(Arel.sql('COUNT(DISTINCT answers.id) DESC, question_records.created_at DESC'))
    when 'answers_asc'
      base_query
        .select('question_records.*, COUNT(DISTINCT answers.id) as answers_count')
        .left_joins(:answers)
        .group('question_records.id')
        .order(Arel.sql('COUNT(DISTINCT answers.id) ASC, question_records.created_at DESC'))
    else # 'date_desc' or default
      base_query.order(created_at: :desc)
    end

    # Load questions for display
    @questions = Question.where(id: @question_records.pluck(:question_id)).index_by(&:id)

    # Get answer counts
    @answer_counts = Answer.where(question_record_id: @question_records.pluck(:id))
      .group(:question_record_id)
      .count

    respond_to do |format|
      format.html { render :show }
      format.turbo_stream if request.xhr?
    end
  end

  # GET /groups/1/questions
  def questions
    # Calculate participation counts for each user
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Load questions with all necessary associations
    @questions = Question.includes(:tags, group_question_tags: [:tag, :created_by])

    # Get voting information for questions in this group
    @group_questions = @group.group_questions.includes(:group_question_votes)
    @group_questions_by_id = @group_questions.index_by(&:question_id)

    # Calculate usage counts
    @question_usage_counts = @group.question_records
      .group(:question_id)
      .count

    # Apply filters
    if params[:filter] == 'used'
      @questions = @questions.where(id: @question_usage_counts.keys)
    elsif params[:filter] == 'unused'
      @questions = @questions.where.not(id: @question_usage_counts.keys)
    end

    # Apply tag filtering
    if params[:tag].present?
      tag_id = params[:tag]
      @questions = @questions.where(
        'questions.id IN (SELECT question_id FROM question_tags WHERE tag_id = ?) OR ' \
        'questions.id IN (SELECT question_id FROM group_question_tags WHERE tag_id = ? AND group_id = ?)',
        tag_id, tag_id, @group.id
      )
    end

    # Apply sorting
    @questions = case params[:sort]
    when 'votes'
      @questions.sort_by { |q| -(@group_questions_by_id[q.id]&.vote_count || 0) }
    when 'usage'
      @questions.sort_by { |q| -(@question_usage_counts[q.id] || 0) }
    else # 'newest' or default
      @questions.order(created_at: :desc)
    end

    respond_to do |format|
      format.html { render :show }
      format.turbo_stream if request.xhr?
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)
    respond_to do |format|
      if @group.save
        # Create an active membership for the group leader
        @group.memberships.create!(user: current_user, active: true)

        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_invite
    @group = Group.find(params[:group_id])
    emails = params[:emails].split(',').map(&:strip)

    successful_invites = []
    failed_invites = []

    emails.each do |email|
      user = User.find_or_create_by_email(email)

      # Check if membership already exists
      existing_membership = @group.memberships.find_by(user: user)

      if existing_membership
        if existing_membership.active?
          failed_invites << "#{email} is already an active member"
        elsif existing_membership.pending?
          failed_invites << "#{email} already has a pending invitation"
        else
          # Reactivate and resend invitation for inactive memberships
          existing_membership.update!(
            active: false,
            invitation_token: SecureRandom.urlsafe_base64(32),
            invitation_accepted_at: nil
          )
          GroupMailer.invite_email(user.email, @group.id, existing_membership.invitation_token).deliver_now
          successful_invites << email
        end
        next
      end

      # Create new membership
      begin
        membership = @group.memberships.create!(
          user: user,
          active: false
        )
        GroupMailer.invite_email(user.email, @group.id, membership.invitation_token).deliver_now
        successful_invites << email
      rescue ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvalid => e
        failed_invites << "#{email} could not be invited (#{e.message})"
      end
    end

    # Set flash messages
    if successful_invites.any?
      flash[:notice] = "Invitations sent to: #{successful_invites.join(', ')}"
    end

    if failed_invites.any?
      flash[:alert] = failed_invites.join(', ')
    end

    redirect_to group_path(@group)
  end

  # Add new method to handle invitation acceptance
  def accept_invitation
    membership = Membership.find_by!(invitation_token: params[:token])

    # Check if user is signed in
    unless current_user
      # Store invitation token in session for post-login processing
      session[:pending_invitation_token] = params[:token]

      # Redirect to sign in with a return path
      return redirect_to new_user_session_path,
        notice: "Please sign in or set up your account to accept the invitation"
    end

    # Ensure the invitation belongs to the current user
    unless membership.user == current_user
      return redirect_to root_path,
        alert: "This invitation was sent to a different email address"
    end

    if membership.pending?
      membership.accept_invitation!
      flash[:notice] = "Welcome to #{membership.group.name}!"
    else
      flash[:alert] = "This invitation is no longer valid"
    end

    redirect_to group_path(membership.group)
  end

  def toggle_member_status
    @group = Group.find(params[:id])
    @member = User.find(params[:member_id])

    if @group.leader?(current_user)
      active_status = params[:active].to_s == 'true'
      @group.toggle_member_status!(@member, active_status, current_user)

      action = active_status ? "activated" : "deactivated"
      flash[:notice] = "Member #{@member.email} has been #{action}"
    else
      flash[:alert] = "Only group leaders can manage member status"
    end

    redirect_to group_path(@group)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :id)
  end
end

app/views/groups/questions/_tags.html.erb
<div class="mt-4">
  <div class="space-y-3">
    <!-- Global Tags -->
    <div class="flex flex-wrap items-start gap-2">
      <span class="text-xs font-medium text-gray-500 mr-1">Global Tags:</span>
      <div class="flex flex-wrap gap-2">
        <% @question.tags.each do |tag| %>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
            <%= tag.name %>
          </span>
        <% end %>
      </div>
    </div>

    <!-- Group Tags -->
    <div class="flex flex-wrap items-start gap-2">
      <span class="text-xs font-medium text-gray-500 mr-1">Group Tags:</span>
      <div class="flex flex-wrap gap-2">
        <% @question.group_question_tags.where(group: @group).includes(:tag, :created_by).each do |group_tag| %>
          <div class="inline-flex items-center bg-indigo-100 rounded-full">
            <span class="px-2.5 py-0.5 text-xs font-medium text-indigo-800">
              <%= group_tag.tag.name %>
              <span class="text-xs text-indigo-600 ml-1" title="Added by <%= group_tag.created_by.email %>">
                (<%= group_tag.created_by.email.split('@').first %>)
              </span>
            </span>
            <% if current_user == @group.leader %>
              <%= button_to remove_tag_group_question_path(@group, @question, tag_id: group_tag.tag.id),
                  method: :delete,
                  class: "p-1 ml-1 mr-1 text-indigo-400 hover:text-indigo-600 hover:bg-indigo-200 rounded-full",
                  title: "Remove this tag",
                  form: { data: { turbo: true, turbo_confirm: "Are you sure you want to remove this tag?" } } do %>
                <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

      <!-- Tag Input Form -->
      <div class="w-full mt-2">
        <%= form_with url: add_tag_group_question_path(@group, @question),
            class: "flex flex-wrap gap-2 items-center",
            data: { controller: "tags", action: "turbo:submit-end->tags#reset" } do |f| %>
          <%= f.text_field :tag_name,
              class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md w-full sm:w-auto",
              placeholder: "Add a group tag...",
              data: { tags_target: "input" } %>
          <%= f.submit "Add",
              class: "mt-2 sm:mt-0 inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/questions/_vote_button_area.html.erb
<div id="vote-button-area-<%= group_question.id %>" class="flex items-center space-x-2">
  <% if group_question.voted_by?(current_user) %>
    <%= button_to unvote_group_question_path(group, question),
        method: :delete,
        class: "inline-flex items-center p-1.5 text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 rounded-full",
        form: { data: { turbo: true } } do %>
      <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd" />
      </svg>
    <% end %>
  <% else %>
    <%= button_to vote_group_question_path(group, question),
        method: :post,
        class: "inline-flex items-center p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-full",
        form: { data: { turbo: true } } do %>
      <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd" />
      </svg>
    <% end %>
  <% end %>
  <span class="text-sm sm:text-base font-medium text-gray-900">
    <%= group_question.vote_count %>
  </span>
</div>

app/views/groups/questions/_vote_buttons.html.erb
<div class="flex items-center space-x-2">
  <% if group_question.voted_by?(current_user) %>
    <%= button_to unvote_group_question_path(group, question),
        method: :delete,
        class: "inline-flex items-center p-1.5 text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 rounded-full",
        form: { data: { turbo: true } } do %>
      <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd" />
      </svg>
    <% end %>
  <% else %>
    <%= button_to vote_group_question_path(group, question),
        method: :post,
        class: "inline-flex items-center p-1.5 text-gray-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-full",
        form: { data: { turbo: true } } do %>
      <svg class="w-5 h-5 sm:w-6 sm:h-6" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd" />
      </svg>
    <% end %>
  <% end %>
  <span class="text-sm sm:text-base font-medium text-gray-900 vote-count-<%= group_question.id %>">
    <%= group_question.vote_count %>
  </span>
</div>

app/views/groups/questions/add_tag.turbo_stream.erb
<%= turbo_stream.update "question_tags" do %>
  <%= render partial: "groups/questions/tags", locals: { question: @question, group: @group } %>
<% end %>

<%= turbo_stream.update_all "form input[type='text']", "" %>

app/views/groups/questions/remove_tag.turbo_stream.erb
<%= turbo_stream.replace "question_tags" do %>
  <%= render "tags" %>
<% end %>