config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # Authentication
  devise_for :users

  # Core Resources
  resources :groups do
    member do
      get 'digests'
      get 'questions'
      post 'send_invite'
      post 'toggle_member_status/:member_id', to: 'groups#toggle_member_status', as: 'toggle_member_status'
    end

    # Nested cycles resource
    resources :cycles, controller: 'group_cycles', only: [:index] do
      member do
        post 'close_early'
      end
      collection do
        post 'send_manual_question'
        post 'send_manual_digest/:cycle_id', to: 'group_cycles#send_manual_digest', as: 'send_manual_digest'
        post 'pause'
        post 'resume'
        patch 'update_mode'
      end
    end

    get 'accept_invitation', on: :collection
    resources :members, only: [:show], controller: 'group_members'
    scope module: :groups do
      resources :questions, only: [:show] do
        member do
          post 'vote'
          post 'add_tag'
          delete 'remove_tag'
          delete 'unvote'
        end
      end
    end
  end
  resources :questions do
    member do
      post 'send', to: 'questions#send_to_group', as: 'send'
    end
  end
  resources :question_records
  resources :answers
  resources :users

  # Custom Actions
  post 'send_random', to: 'questions#send_random_question'
  post 'inbound', to: 'email_response#create_from_inbound_hook'
  post 'answer', to: 'answers#create_from_form'

  # Admin Section
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'

    get 'dashboard/visits', to: 'dashboard#visits'
    get 'dashboard/emails', to: 'dashboard#emails'
    get 'dashboard/events', to: 'dashboard#events'
    get 'dashboard/users', to: 'dashboard#users'
    get 'dashboard/users/:id', to: 'dashboard#user_details', as: 'dashboard_user_details'
    get 'dashboard/email_reply_stats', to: 'dashboard#email_reply_stats', as: 'email_reply_stats'

    # Chart data endpoints
    get 'dashboard/daily_visits_data', to: 'dashboard#daily_visits_data'
    get 'dashboard/hourly_visits_data', to: 'dashboard#hourly_visits_data'
    get 'dashboard/countries_data', to: 'dashboard#countries_data'
    get 'dashboard/devices_data', to: 'dashboard#devices_data'
    get 'dashboard/emails_data', to: 'dashboard#emails_data'
    get 'dashboard/events_data', to: 'dashboard#events_data'
    get 'dashboard/regions_data', to: 'dashboard#regions_data'
    get 'dashboard/cities_data', to: 'dashboard#cities_data'
    get 'dashboard/user_activity_data', to: 'dashboard#user_activity_data'
    get 'dashboard/group_activity_data', to: 'dashboard#group_activity_data'

    get 'recent_signups', to: 'dashboard#recent_signups'

    get 'dashboard/groups', to: 'dashboard#groups'
    get 'dashboard/group_details/:id', to: 'dashboard#group_details', as: 'group_details'
  end

  # Development Tools
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/groups/questions_controller.rb
module Groups
  class QuestionsController < ApplicationController
    before_action :set_group
    before_action :set_question

    def show
      # Get usage statistics
      @usage_count = @group.question_records.where(question_id: @question.id).count

      # Get all instances this question was asked
      @question_records = @group.question_records
        .where(question_id: @question.id)
        .order(created_at: :desc)

      # Simple total answers count
      @total_answers = Answer.where(question_record_id: @question_records.pluck(:id)).count

      # Get voting information
      @group_question = @group.group_questions.find_by(question: @question)
      @voter_count = @group_question&.group_question_votes&.count || 0

      # Get similar questions based on tags
      @similar_questions = Question.joins(:tags)
        .where(tags: { id: @question.tags.pluck(:id) })
        .where.not(id: @question.id)
        .distinct
        .limit(5)
    end

    def add_tag
      # Ensure user is a member of the group
      unless @group.users.include?(current_user)
        redirect_to group_question_path(@group, @question), alert: "Only group members can add tags"
        return
      end

      tag = Tag.find_or_create_by(name: params[:tag_name].strip.downcase)

      unless @question.group_question_tags.exists?(group: @group, tag: tag)
        @question.group_question_tags.create!(
          group: @group,
          tag: tag,
          created_by: current_user  # Track who created the tag
        )
      end

      @question.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to group_question_path(@group, @question) }
      end
    end

    def remove_tag
      # Only group leaders can remove tags
      unless current_user == @group.leader
        redirect_to group_question_path(@group, @question), alert: "Only group leaders can remove tags"
        return
      end

      tag = Tag.find(params[:tag_id])
      group_tag = @question.group_question_tags.find_by(group: @group, tag: tag)
      group_tag&.destroy

      @question.reload

      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to group_question_path(@group, @question) }
      end
    end

    def vote
      @group_question = @group.group_questions.find_or_create_by!(question: @question)

      if @group_question.voted_by?(current_user)
        redirect_back(fallback_location: group_question_path(@group, @question), alert: "You have already voted for this question")
        return
      end

      vote = @group_question.group_question_votes.build(user: current_user)

      if vote.save
        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: [
              turbo_stream.replace("vote-button-area-#{@group_question.id}",
                partial: 'groups/questions/vote_button_area',
                locals: { group: @group, question: @question, group_question: @group_question }
              ),
              turbo_stream.replace_all(".question-#{@question.id}-vote-count",
                @group_question.vote_count.to_s)
            ]
          }
          format.html { redirect_back(fallback_location: group_question_path(@group, @question), notice: "Vote recorded") }
        end
      else
        redirect_back(fallback_location: group_question_path(@group, @question), alert: vote.errors.full_messages.to_sentence)
      end
    end

    def unvote
      @group_question = @group.group_questions.find_by!(question: @question)
      vote = @group_question.group_question_votes.find_by(user: current_user)

      if vote&.destroy
        respond_to do |format|
          format.turbo_stream {
            render turbo_stream: [
              turbo_stream.replace("vote-button-area-#{@group_question.id}",
                partial: 'groups/questions/vote_button_area',
                locals: { group: @group, question: @question, group_question: @group_question }
              ),
              turbo_stream.replace_all(".question-#{@question.id}-vote-count",
                @group_question.vote_count.to_s)
            ]
          }
          format.html { redirect_back(fallback_location: group_question_path(@group, @question), notice: "Vote removed") }
        end
      else
        redirect_back(fallback_location: group_question_path(@group, @question), alert: "Unable to remove vote")
      end
    end

    private

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_question
      @question = Question.find(params[:id])
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :questions, :digests]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # Calculate participation counts for each user (needed for both tabs)
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Redirect to the appropriate tab action
    if params[:tab] == 'questions'
      redirect_to questions_group_path(@group, request.query_parameters.except(:tab))
    elsif params[:tab] == 'cycles' && current_user == @group.leader
      redirect_to group_cycles_path(@group, request.query_parameters.except(:tab))
    else
      redirect_to digests_group_path(@group, request.query_parameters.except(:tab))
    end
  end

  # GET /groups/1/digests
  def digests
    # Calculate participation counts for each user
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Q&A Digests tab
    base_query = @group.question_records
      .includes(:question, :answers)

    # Apply sorting for Q&A Digests
    @question_records = case params[:sort]
    when 'date_asc'
      base_query.order(created_at: :asc)
    when 'answers_desc'
      base_query
        .select('question_records.*, COUNT(DISTINCT answers.id) as answers_count')
        .left_joins(:answers)
        .group('question_records.id')
        .order(Arel.sql('COUNT(DISTINCT answers.id) DESC, question_records.created_at DESC'))
    when 'answers_asc'
      base_query
        .select('question_records.*, COUNT(DISTINCT answers.id) as answers_count')
        .left_joins(:answers)
        .group('question_records.id')
        .order(Arel.sql('COUNT(DISTINCT answers.id) ASC, question_records.created_at DESC'))
    else # 'date_desc' or default
      base_query.order(created_at: :desc)
    end

    # Load questions for display
    @questions = Question.where(id: @question_records.pluck(:question_id)).index_by(&:id)

    # Get answer counts
    @answer_counts = Answer.where(question_record_id: @question_records.pluck(:id))
      .group(:question_record_id)
      .count

    respond_to do |format|
      format.html { render :show }
      format.turbo_stream if request.xhr?
    end
  end

  # GET /groups/1/questions
  def questions
    # Calculate participation counts for each user
    @participation_counts = Answer.joins(:question_record)
      .where(question_records: { group_id: @group.id })
      .group(:user_id)
      .distinct
      .count

    # Load questions with all necessary associations
    @questions = Question.includes(:tags, group_question_tags: [:tag, :created_by])

    # Get voting information for questions in this group
    @group_questions = @group.group_questions.includes(:group_question_votes)
    @group_questions_by_id = @group_questions.index_by(&:question_id)

    # Calculate usage counts
    @question_usage_counts = @group.question_records
      .group(:question_id)
      .count

    # Apply filters
    if params[:filter] == 'used'
      @questions = @questions.where(id: @question_usage_counts.keys)
    elsif params[:filter] == 'unused'
      @questions = @questions.where.not(id: @question_usage_counts.keys)
    end

    # Apply tag filtering
    if params[:tag].present?
      tag_id = params[:tag]
      @questions = @questions.where(
        'questions.id IN (SELECT question_id FROM question_tags WHERE tag_id = ?) OR ' \
        'questions.id IN (SELECT question_id FROM group_question_tags WHERE tag_id = ? AND group_id = ?)',
        tag_id, tag_id, @group.id
      )
    end

    # Apply sorting
    @questions = case params[:sort]
    when 'votes'
      @questions.sort_by { |q| -(@group_questions_by_id[q.id]&.vote_count || 0) }
    when 'usage'
      @questions.sort_by { |q| -(@question_usage_counts[q.id] || 0) }
    else # 'newest' or default
      @questions.order(created_at: :desc)
    end

    respond_to do |format|
      format.html { render :show }
      format.turbo_stream if request.xhr?
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)
    respond_to do |format|
      if @group.save
        # Create an active membership for the group leader
        @group.memberships.create!(user: current_user, active: true)

        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_invite
    @group = Group.find(params[:group_id])
    emails = params[:emails].split(',').map(&:strip)

    successful_invites = []
    failed_invites = []

    emails.each do |email|
      user = User.find_or_create_by_email(email)

      # Check if membership already exists
      existing_membership = @group.memberships.find_by(user: user)

      if existing_membership
        if existing_membership.active?
          failed_invites << "#{email} is already an active member"
        elsif existing_membership.pending?
          failed_invites << "#{email} already has a pending invitation"
        else
          # Reactivate and resend invitation for inactive memberships
          existing_membership.update!(
            active: false,
            invitation_token: SecureRandom.urlsafe_base64(32),
            invitation_accepted_at: nil
          )
          GroupMailer.invite_email(user.email, @group.id, existing_membership.invitation_token).deliver_now
          successful_invites << email
        end
        next
      end

      # Create new membership
      begin
        membership = @group.memberships.create!(
          user: user,
          active: false
        )
        GroupMailer.invite_email(user.email, @group.id, membership.invitation_token).deliver_now
        successful_invites << email
      rescue ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvalid => e
        failed_invites << "#{email} could not be invited (#{e.message})"
      end
    end

    # Set flash messages
    if successful_invites.any?
      flash[:notice] = "Invitations sent to: #{successful_invites.join(', ')}"
    end

    if failed_invites.any?
      flash[:alert] = failed_invites.join(', ')
    end

    redirect_to group_path(@group)
  end

  # Add new method to handle invitation acceptance
  def accept_invitation
    membership = Membership.find_by!(invitation_token: params[:token])

    # Check if user is signed in
    unless current_user
      # Store invitation token in session for post-login processing
      session[:pending_invitation_token] = params[:token]

      # Redirect to sign in with a return path
      return redirect_to new_user_session_path,
        notice: "Please sign in or set up your account to accept the invitation"
    end

    # Ensure the invitation belongs to the current user
    unless membership.user == current_user
      return redirect_to root_path,
        alert: "This invitation was sent to a different email address"
    end

    if membership.pending?
      membership.accept_invitation!
      flash[:notice] = "Welcome to #{membership.group.name}!"
    else
      flash[:alert] = "This invitation is no longer valid"
    end

    redirect_to group_path(membership.group)
  end

  def toggle_member_status
    @group = Group.find(params[:id])
    @member = User.find(params[:member_id])

    if @group.leader?(current_user)
      active_status = params[:active].to_s == 'true'
      @group.toggle_member_status!(@member, active_status, current_user)

      action = active_status ? "activated" : "deactivated"
      flash[:notice] = "Member #{@member.email} has been #{action}"
    else
      flash[:alert] = "Only group leaders can manage member status"
    end

    redirect_to group_path(@group)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :id)
  end
end

app/views/groups/_cycles.html.erb
<div class="bg-white p-4 sm:p-6 rounded-lg shadow-sm">
  <h2 class="text-xl font-semibold mb-4">Question Cycle Management</h2>

  <!-- Mode Selection -->
  <div class="mb-6 border-b pb-4">
    <h3 class="text-lg font-medium mb-2">Question Delivery Mode</h3>

    <% if @group.automatic_mode? %>
      <div class="bg-green-50 text-green-700 p-3 rounded-md mb-3">
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
          <span>Automatic Weekly Questions (Current)</span>
        </div>
      </div>
      <%= button_to "Switch to Manual Mode", update_mode_group_cycles_path(@group, mode: 'manual'), method: :patch, class: "px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300" %>
    <% else %>
      <div class="bg-blue-50 text-blue-700 p-3 rounded-md mb-3">
        <div class="flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
          <span>Manual Question Control (Current)</span>
        </div>
      </div>
      <%= button_to "Switch to Automatic Mode", update_mode_group_cycles_path(@group, mode: 'automatic'), method: :patch, class: "px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300" %>
    <% end %>
  </div>

  <!-- Pause Controls (only for automatic mode) -->
  <% if @group.automatic_mode? %>
    <div class="mb-6 border-b pb-4">
      <h3 class="text-lg font-medium mb-2">Pause/Resume Automatic Questions</h3>

      <% if @group.paused? %>
        <div class="bg-yellow-50 text-yellow-700 p-3 rounded-md mb-3">
          <div class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
            <span>Questions paused until <%= @group.paused_until.strftime('%B %d, %Y') %></span>
          </div>
        </div>
        <div style="margin-bottom: 16px;">
          <%= button_to resume_group_cycles_path(@group), method: :post, style: "background-color: #2563eb; color: white; padding: 8px 16px; border-radius: 4px; font-weight: 500; cursor: pointer; display: inline-block; border: none;" do %>
            Resume Now
          <% end %>
        </div>
      <% else %>
        <div class="bg-gray-100 border border-gray-300 p-4 rounded-md mb-4" style="padding: 16px; border: 1px solid #ccc; border-radius: 6px; margin-bottom: 16px;">
          <%= form_with url: pause_group_cycles_path(@group), method: :post, id: "pause-form" do |f| %>
            <div class="flex flex-col gap-4" style="display: flex; flex-direction: column; gap: 16px;">
              <div>
                <label class="block font-medium text-gray-700 mb-2" style="display: block; font-weight: 500; margin-bottom: 8px;">Pause until:</label>
                <%= f.date_field :pause_until, class: "w-full rounded border p-2", style: "width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;", min: Date.current, required: true %>
              </div>

              <button type="submit" style="background-color: #ca8a04; color: white; padding: 8px 16px; border-radius: 4px; font-weight: 500; cursor: pointer; display: inline-block; border: none;">
                Pause Questions
              </button>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Current Active Question -->
  <div class="mb-6 border-b pb-4">
    <h3 class="text-lg font-medium mb-2">Current Active Question</h3>

    <% if active_cycle = @group.current_active_cycle %>
      <div class="bg-white border rounded-lg p-4 mb-4">
        <div class="font-medium mb-1"><%= active_cycle.question.question %></div>
        <div class="text-sm text-gray-600 mb-2">
          <%= active_cycle.answer_count %> answers received
          <span class="mx-2">•</span>
          <%= active_cycle.remaining_days %> days remaining
        </div>
        <div class="flex flex-wrap gap-2 items-center">
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
            Active until <%= active_cycle.end_date.strftime("%b %d") %>
          </span>
          <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
            Digest on <%= active_cycle.digest_date.strftime("%b %d") %>
          </span>

          <!-- Close Early Button -->
          <div class="ml-auto mt-2 sm:mt-0">
            <%= button_to close_early_group_cycle_path(@group, active_cycle),
                        method: :post,
                        style: "background-color: #ca8a04; color: white; padding: 6px 12px; border-radius: 4px; font-weight: 500; cursor: pointer; border: none; font-size: 0.875rem;",
                        data: { confirm: "Are you sure? This will stop collecting answers and move the question to 'Awaiting Digest' status." } do %>
              Close Question Early
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <p class="text-gray-500 italic">No active question at the moment.</p>
    <% end %>
  </div>

  <!-- Scheduled Questions -->
  <div style="margin-bottom: 2rem; padding-bottom: 1.5rem; border-bottom: 1px solid #e5e7eb;">
    <h3 class="text-lg font-medium mb-2">Upcoming Questions</h3>

    <% if upcoming_cycles = @group.upcoming_cycles.presence %>
      <div class="space-y-2">
        <% upcoming_cycles.each do |cycle| %>
          <div class="bg-white border rounded-lg p-3">
            <div class="font-medium"><%= cycle.question.question %></div>
            <div class="text-sm text-gray-600 mt-1">
              Starts on <%= cycle.start_date.strftime("%b %d, %Y") %>
              <% if cycle.manual? %>
                <span class="ml-2 inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800">
                  Manual
                </span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-gray-500 italic">No upcoming questions scheduled.</p>
    <% end %>
  </div>

  <!-- Manual Questions (for both modes) -->
  <div style="margin-top: 2rem; margin-bottom: 1rem;">
    <h3 class="text-lg font-medium mb-3">Send a Manual Question</h3>

    <div class="bg-gray-50 p-4 rounded-lg" style="padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px;">
      <%= form_with url: send_manual_question_group_cycles_path(@group), method: :post, id: "send-question-form" do |f| %>
        <div class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-1" style="display: block; margin-bottom: 4px; font-weight: 500;">Select a question:</label>
          <%= f.collection_select :question_id,
                                @group.available_questions.order(created_at: :desc),
                                :id,
                                :question,
                                { prompt: "Choose a question..." },
                                { class: "w-full rounded-md border border-gray-300 p-2", style: "width: 100%; padding: 8px; border: 1px solid #d1d5db; border-radius: 6px;" } %>
        </div>
        <button type="submit" style="background-color: #2563eb; color: white; padding: 8px 16px; border-radius: 4px; font-weight: 500; cursor: pointer; display: inline-block; border: none;">
          Send Question Now
        </button>
      <% end %>
    </div>
  </div>

  <!-- Recently Closed Cycles -->
  <div>
    <h3 class="text-lg font-medium mb-2">Recent Cycles</h3>

    <% if recent_cycles = @group.recent_cycles.presence %>
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Question</th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dates</th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
              <th scope="col" class="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Answers</th>
              <th scope="col" class="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% recent_cycles.each do |cycle| %>
              <tr>
                <td class="px-4 py-3 text-sm text-gray-900 max-w-xs truncate"><%= cycle.question.question %></td>
                <td class="px-4 py-3 text-sm text-gray-500">
                  <%= cycle.start_date.strftime("%b %d, %Y") %> - <%= cycle.end_date.strftime("%b %d, %Y") %>
                </td>
                <td class="px-4 py-3 text-sm">
                  <% if cycle.status == "active" %>
                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
                      Active
                    </span>
                  <% elsif cycle.status == "closed" %>
                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-yellow-100 text-yellow-800">
                      Awaiting Digest
                    </span>
                  <% elsif cycle.status == "completed" %>
                    <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">
                      Completed
                    </span>
                  <% end %>
                </td>
                <td class="px-4 py-3 text-sm text-gray-500"><%= cycle.answer_count %></td>
                <td class="px-4 py-3 text-sm text-right">
                  <% if cycle.status == "active" %>
                    <%= button_to "Close Early",
                                close_early_group_cycle_path(@group, cycle),
                                method: :post,
                                style: "display: inline-block; background-color: #ca8a04; color: white; padding: 4px 8px; border-radius: 4px; font-weight: 500; cursor: pointer; border: none; font-size: 0.75rem;",
                                data: { confirm: "Are you sure? This will stop collecting answers for this question." } %>
                  <% elsif cycle.status == "closed" %>
                    <%= button_to "Send Digest",
                                 send_manual_digest_group_cycles_path(@group, cycle_id: cycle.id),
                                 method: :post,
                                 class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="text-gray-500 italic">No recent question cycles.</p>
    <% end %>
  </div>
</div>

<!-- JavaScript for form handling -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Get the pause form
    const pauseForm = document.getElementById('pause-form');

    if (pauseForm) {
      pauseForm.addEventListener('submit', function(event) {
        // Get the date input
        const dateInput = this.querySelector('input[name="pause_until"]');

        if (!dateInput.value) {
          event.preventDefault();
          alert('Please select a date before submitting');
        } else {
          console.log('Submitting pause form with date: ' + dateInput.value);
        }
      });
    }
  });
</script>